### ISSUE TITLE
Problemas con el cambio de version de 2 a 3.

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce-subscriptions#54]
Estimado equipo de soporte,

Me dirijo a ustedes tras haber experimentado un inconveniente relacionado con la reciente actualización del plug-in a la versión 3.1.1. Hemos observado que, después de esta actualización, las suscripciones creadas con la versión 2.x no se reflejan adecuadamente en la consola de Mobbex/Fressa cuando se renuevan. Como resultado, estas suscripciones quedan como "pendientes de pago" en nuestra plataforma de WooCommerce.

Para brindarles un contexto, nuestra empresa comercializa licencias de software mediante un modelo de suscripción mensual. Contamos con clientes que han estado con nosotros desde el 2021, y sus pagos se procesaban correctamente cada mes hasta que se realizó el cambio de versión del plug-in.

Mi entendimiento es que, en la versión 2.x, las suscripciones se vinculaban a través de la orden de WooCommerce con el suscriptor y la suscripción en Mobbex. Sin embargo, con la nueva actualización, parece que la vinculación se hace a nivel de producto en lugar de ordenes.

Nuestra preocupación principal es cómo podemos restaurar la funcionalidad de las suscripciones activas sin causar inconvenientes a nuestros clientes, evitando que tengan que realizar una nueva compra.

Para su referencia, utilizamos las siguientes herramientas:

WooCommerce
WooCommerce-subscriptions
https://woo.com/es-es/products/woocommerce-subscriptions/
Agradecería mucho su orientación y apoyo en esta situación. Estoy a la espera de su respuesta y quedo disponible para proporcionar cualquier información adicional que puedan necesitar.

Saludos cordiales,

**Comment by webadapta** [comment]
Mismo problema. Alguna novedad? @jlmobbex  @mobbexLuis @EMunozMobbex

**Comment by jlmobbex** [comment]
Buen día @erpwoosync y @webadapta, gracias por sus comentarios!

El cambio en la vinculación de las suscripciones fue algo a lo que prestamos especial atención al momento de desarrollar la versión 3.0. Para dar retrocompatibilidad se implementó un script de migración que permite que las subs antiguas (<3.0) sigan ejecutándose normalmente. 

Veo muy probable que se esté dando un error al momento de ejecutar este proceso de migración, así les pido a ambos si pueden brindarnos los logs que genera el plugin.

Para obtenerlos deben instalar Simple History Log e intentar replicar nuevamente el inconveniente (luego estos aparecen en el panel de Simple History). También es posible que existan registros en la [sección de logs de WooCommerce](https://woo.com/document/understanding-the-woocommerce-system-status-report/#error-logs) (es probable si son errores fatales).

En caso de que haya información sensible les pido que se comuniquen a ayuda@mobbex.com para compartirlos por ese medio. Saludos!

**Comment by webadapta** [comment]
Hola @jlmobbex,
gracias por la respuesta. Te paso los log que encontré en Woocommerce:

2023-11-15T15:33:05+00:00 CRITICAL Uncaught Error: Call to a member function calculateDates() on null in /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php:267
Stack trace:
#0 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php(239): WC_Gateway_Mbbx_Subs->process_webhook('e6f0bbc980e1c93...', Array, 'subscription:ex...', '2504')
#1 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_Gateway_Mbbx_Subs->mobbex_subs_webhook('')
#2 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /home/xxxxxl/yyyyy/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#5 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_API->handle_api_requests(Object(WP))
#6 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /home/guadacabal en /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php en la línea 267

2023-11-15T15:33:22+00:00 CRITICAL Uncaught Error: Call to a member function calculateDates() on null in /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php:267
Stack trace:
#0 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php(239): WC_Gateway_Mbbx_Subs->process_webhook('e6f0bbc980e1c93...', Array, 'subscription:ex...', '2504')
#1 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_Gateway_Mbbx_Subs->mobbex_subs_webhook('')
#2 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /home/xxxxxl/yyyyy/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#5 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_API->handle_api_requests(Object(WP))
#6 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /home/guadacabal en /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php en la línea 267

2023-11-15T15:33:54+00:00 CRITICAL Uncaught Error: Call to a member function calculateDates() on null in /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php:267
Stack trace:
#0 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php(239): WC_Gateway_Mbbx_Subs->process_webhook('e6f0bbc980e1c93...', Array, 'subscription:ex...', '2504')
#1 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_Gateway_Mbbx_Subs->mobbex_subs_webhook('')
#2 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /home/xxxxxl/yyyyy/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#5 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(324): WC_API->handle_api_requests(Object(WP))
#6 /home/xxxxxl/yyyyy/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /home/guadacabal en /home/xxxxxl/yyyyy/wp-content/plugins/woocommerce-mobbex-subs/includes/gateway.php en la línea 267

**Comment by erpwoosync** [comment]
@jlmobbex He instalado el plugin que comentas y he habilitado el debug de Wordpress, y no tengo log de errores, tambien he desactivado y vuelto a activar el plugin de Mobbex Subscriptions for WooCommerce 3.1.1, y las suscripciones antiguas, cuando se ejecutan las renovacion quedan pendientes de pago.


Mi web solo log

[22-Nov-2023 19:35:44 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:45 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:47 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:47 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:48 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:48 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:48 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:50 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:50 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:50 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:50 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:51 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:51 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:51 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:51 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:51 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:52 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:52 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:53 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:53 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:53 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:53 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031
[22-Nov-2023 19:35:55 UTC] PHP Notice:  La función wpdb::prepare ha sido llamada de forma incorrecta. El argumento de la consulta wpdb::prepare() debe tener un marcador de posición. Por favor, ve <a>depuración en WordPress</a> para más información. (Este mensaje fue añadido en la versión 3.9.0). in /home/erpwoosy/public_html/wp-includes/functions.php on line 6031

**Comment by jlmobbex** [comment]
Buenas tardes! El año pasado no utilizamos este canal para revisar inconvenientes en el plugin. Les pido que si aún siguen con el mismo prueben con la última versión del plugin o se comuniquen con ayuda@mobbex.com.
