### ISSUE TITLE
PHP fatal error al actualizar a la versión 2.5.0 de WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by leandroprz** [mobbexco/woocommerce-subscriptions#58]
Luego de actualizar WooCommerce PayPal Payments a la v2.5.0 empecé a ver este mensaje de error:

```
Fatal error: Uncaught TypeError: WooCommerce\PayPalCommerce\WcSubscriptions\WcSubscriptionsModule::WooCommerce\PayPalCommerce\WcSubscriptions\{closure}(): Argument #1 ($methods) must be of type array, null given, called in D:\laragon\www\lp\wp-includes\class-wp-hook.php on line 324 and defined in D:\laragon\www\lp\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-wc-subscriptions\src\WcSubscriptionsModule.php:161 Stack trace: #0 D:\laragon\www\lp\wp-includes\class-wp-hook.php(324): WooCommerce\PayPalCommerce\WcSubscriptions\WcSubscriptionsModule->WooCommerce\PayPalCommerce\WcSubscriptions\{closure}(NULL) #1 D:\laragon\www\lp\wp-includes\plugin.php(205): WP_Hook->apply_filters(NULL, Array) #2 D:\laragon\www\lp\wp-content\plugins\woocommerce\includes\class-wc-payment-gateways.php(333): apply_filters('woocommerce_ava...', Array) #3 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\Tasks\Payments.php(93): WC_Payment_Gateways->get_available_payment_gateways() #4 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\Tasks\Payments.php(71): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments::has_gateways() #5 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments.php(125): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments->is_complete() #6 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\TaskList.php(304): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments->can_view() #7 [internal function]: Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->Automattic\WooCommerce\Admin\Features\OnboardingTasks\{closure}(Object(Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments)) #8 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\TaskList.php(305): array_filter(Array, Object(Closure)) #9 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\TaskList.php(171): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->get_viewable_tasks() #10 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\TaskLists.php(349): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->is_visible() #11 [internal function]: Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::Automattic\WooCommerce\Admin\Features\OnboardingTasks\{closure}(Object(Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList)) #12 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Admin\Features\OnboardingTasks\TaskLists.php(350): array_filter(Array, Object(Closure)) #13 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Internal\Admin\Onboarding\OnboardingSetupWizard.php(217): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::get_visible() #14 D:\laragon\www\lp\wp-includes\class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\Onboarding\OnboardingSetupWizard->component_settings(Array) #15 D:\laragon\www\lp\wp-includes\plugin.php(205): WP_Hook->apply_filters(Array, Array) #16 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Internal\Admin\WCAdminSharedSettings.php(61): apply_filters('woocommerce_adm...', Array) #17 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Blocks\Assets\AssetDataRegistry.php(268): Automattic\WooCommerce\Internal\Admin\WCAdminSharedSettings->Automattic\WooCommerce\Internal\Admin\{closure}() #18 D:\laragon\www\lp\wp-content\plugins\woocommerce\src\Blocks\Assets\AssetDataRegistry.php(393): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->execute_lazy_data() #19 D:\laragon\www\lp\wp-includes\class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('') #20 D:\laragon\www\lp\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #21 D:\laragon\www\lp\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #22 D:\laragon\www\lp\wp-admin\admin-footer.php(95): do_action('admin_print_foo...') #23 D:\laragon\www\lp\wp-admin\index.php(212): require_once('D:\\laragon\\www\\...') #24 {main} thrown in D:\laragon\www\lp\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-wc-subscriptions\src\WcSubscriptionsModule.php on line 161

Ha habido un error crítico en esta web. Por favor, comprueba la bandeja de entrada del correo electrónico del administrador de tu sitio para obtener instrucciones.
```

Al desactivar el plugin Mobbex Subscriptions for WooCommerce el error desaparece. Por lo visto no son compatibles.

**Comment by leandroprz** [comment]
Lo solucionaron en la v2.5.1 del plugin de PayPal.
